apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-app-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: short-app-db
  template:
    metadata:
      labels:
        components: short-app-db
    spec:
      containers:
        - name: short-app-db
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: demo
            - name: POSTGRES_USER
              value: demo
            - name: POSTGRES_PASSWORD
              value: demo
          resources:
            limits:
              memory: "500Mi"
              cpu: "300m"