apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-app-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: short-app-db
  template:
    metadata:
      labels:
        components: short-app-db
    spec:
      containers:
        - name: short-app-db
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: short-app-db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: short-app-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: short-app-db-secret
                  key: POSTGRES_PASSWORD
          resources:
            limits:
              memory: "500Mi"
              cpu: "300m"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              subPath: "postgress"
              name: short-app-db-data
      volumes:
        - name: short-app-db-data
          persistentVolumeClaim:
            claimName: short-app-db-pvc
      restartPolicy: Always
